// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/*
  Class: Topics Software Engineering
  Date: 11/13/2022
  Author: Christian Alberto Gomez
  Assignment: Final Project
 */

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4v5DV9y8c2EBylyW7ShJ70sk1NaPA_is',
    appId: '1:1017237844174:web:a9f6a4e3dccf11e5b7609f',
    messagingSenderId: '1017237844174',
    projectId: 'pokedex-final-project',
    authDomain: 'pokedex-final-project.firebaseapp.com',
    storageBucket: 'pokedex-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASeNxnrGptymtwz3GJro7RYnFD6TBi-z0',
    appId: '1:1017237844174:android:b03a02e08ea362e2b7609f',
    messagingSenderId: '1017237844174',
    projectId: 'pokedex-final-project',
    storageBucket: 'pokedex-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVs3hNamGMq6zommz1stpOjI2f2ozIcls',
    appId: '1:1017237844174:ios:087cdd51c14af994b7609f',
    messagingSenderId: '1017237844174',
    projectId: 'pokedex-final-project',
    storageBucket: 'pokedex-final-project.appspot.com',
    iosClientId: '1017237844174-vjvrjr207lk31hn4a5oajol8eifum8eb.apps.googleusercontent.com',
    iosBundleId: 'ProkedexFinalProject.com.pokedexFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVs3hNamGMq6zommz1stpOjI2f2ozIcls',
    appId: '1:1017237844174:ios:087cdd51c14af994b7609f',
    messagingSenderId: '1017237844174',
    projectId: 'pokedex-final-project',
    storageBucket: 'pokedex-final-project.appspot.com',
    iosClientId: '1017237844174-vjvrjr207lk31hn4a5oajol8eifum8eb.apps.googleusercontent.com',
    iosBundleId: 'ProkedexFinalProject.com.pokedexFinalProject',
  );
}
